package steam

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/binary"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

// Discord names a Rich Presence after the application that published it, not
// after anything in the payload. Publishing under our own app therefore reads
// "Playing glow.moe" no matter what the details say. Discord already has an
// application registered for most games, so connecting under the game's own id
// makes the headline read "Playing Unturned" instead.
//
// The table maps Steam appid -> Discord application id, generated by
// scripts/gen-steam-map.sh from Discord's public detectable-games list.
//
// The embedded copy below is the always-available fallback. At runtime we also
// pull a fresher copy from glow.moe (see RefreshFromServer), which regenerates
// it weekly. We fetch it from glow.moe rather than discord.com because Discord
// is blocked in some of the countries glow is most used in, so a direct fetch
// would fail exactly where it is needed most; glow.moe is reachable there.
//
//go:embed steam-apps.bin.gz
var appMapGz []byte

const recordSize = 12 // uint32 appid + uint64 discord id, little endian

var (
	appMapOnce sync.Once
	appMapMu   sync.RWMutex
	appMap     []byte // sorted fixed-width records; searched, never unpacked whole
)

func configDir() (string, error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, "glow-collector"), nil
}

// decode gunzips a map blob and validates it is a whole number of records.
func decode(gz []byte) []byte {
	zr, err := gzip.NewReader(bytes.NewReader(gz))
	if err != nil {
		return nil
	}
	defer zr.Close()
	b, err := io.ReadAll(zr)
	if err != nil || len(b) == 0 || len(b)%recordSize != 0 {
		return nil
	}
	return b
}

func loadAppMap() {
	// Prefer a fresher map downloaded from glow.moe; fall back to the embedded
	// one so we always work offline and on the very first run.
	if dir, err := configDir(); err == nil {
		if gz, err := os.ReadFile(filepath.Join(dir, "steam-apps.bin.gz")); err == nil {
			if b := decode(gz); b != nil {
				appMap = b
				return
			}
		}
	}
	appMap = decode(appMapGz)
}

// DiscordAppID returns the Discord application registered for a Steam game, so
// the presence can be published under it. ok is false for games Discord does not
// know, which is the caller's cue to fall back to its own application.
func DiscordAppID(steamAppID int) (uint64, bool) {
	if steamAppID <= 0 {
		return 0, false
	}
	appMapOnce.Do(loadAppMap)
	appMapMu.RLock()
	m := appMap
	appMapMu.RUnlock()
	n := len(m) / recordSize
	if n == 0 {
		return 0, false
	}
	want := uint32(steamAppID)
	i := sort.Search(n, func(i int) bool {
		return binary.LittleEndian.Uint32(m[i*recordSize:]) >= want
	})
	if i >= n || binary.LittleEndian.Uint32(m[i*recordSize:]) != want {
		return 0, false
	}
	return binary.LittleEndian.Uint64(m[i*recordSize+4:]), true
}

// RefreshFromServer pulls the latest map from glow.moe/api/steam-map (which
// regenerates it weekly from Discord's detectable list). Best-effort: any
// failure or a 304 leaves the current cached/embedded map untouched. On a fresh
// map it caches the gzip + its ETag next to config.json and hot-swaps the table.
func RefreshFromServer(base string) {
	base = strings.TrimRight(base, "/")
	if base == "" {
		return
	}
	appMapOnce.Do(loadAppMap)

	dir, derr := configDir()
	req, err := http.NewRequest(http.MethodGet, base+"/api/steam-map", nil)
	if err != nil {
		return
	}
	if derr == nil {
		if et, err := os.ReadFile(filepath.Join(dir, "steam-apps.etag")); err == nil && len(et) > 0 {
			req.Header.Set("If-None-Match", string(et))
		}
	}
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK { // 304 Not Modified included
		return
	}
	gz, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20)) // 4 MB cap
	if err != nil {
		return
	}
	b := decode(gz)
	if b == nil {
		return // never accept a corrupt map
	}
	if derr == nil {
		_ = os.MkdirAll(dir, 0o755)
		_ = os.WriteFile(filepath.Join(dir, "steam-apps.bin.gz"), gz, 0o644)
		if et := resp.Header.Get("ETag"); et != "" {
			_ = os.WriteFile(filepath.Join(dir, "steam-apps.etag"), []byte(et), 0o644)
		}
	}
	appMapMu.Lock()
	appMap = b
	appMapMu.Unlock()
}

// RefreshLoop refreshes the map now and then once a week, in the background.
func RefreshLoop(base string) {
	RefreshFromServer(base)
	t := time.NewTicker(7 * 24 * time.Hour)
	defer t.Stop()
	for range t.C {
		RefreshFromServer(base)
	}
}
