package steam

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/binary"
	"io"
	"sort"
	"sync"
)

// Discord names a Rich Presence after the application that published it, not
// after anything in the payload. Publishing under our own app therefore reads
// "Playing glow.moe" no matter what the details say. Discord already has an
// application registered for most games, so connecting under the game's own id
// makes the headline read "Playing Unturned" instead.
//
// The table maps Steam appid -> Discord application id and is generated by
// scripts/gen-steam-map.sh from Discord's public detectable-games list.
//
// It is embedded rather than downloaded: Discord is blocked in some of the
// countries glow is most used in, so a runtime fetch would fail exactly where it
// is needed most. 169 KB is a fair price for working offline everywhere.
//
//go:embed steam-apps.bin.gz
var appMapGz []byte

const recordSize = 12 // uint32 appid + uint64 discord id, little endian

var (
	appMapOnce sync.Once
	appMap     []byte // sorted fixed-width records; searched, never unpacked whole
)

func loadAppMap() {
	zr, err := gzip.NewReader(bytes.NewReader(appMapGz))
	if err != nil {
		return
	}
	defer zr.Close()
	b, err := io.ReadAll(zr)
	if err != nil || len(b)%recordSize != 0 {
		return
	}
	appMap = b
}

// DiscordAppID returns the Discord application registered for a Steam game, so
// the presence can be published under it. ok is false for games Discord does not
// know, which is the caller's cue to fall back to its own application.
func DiscordAppID(steamAppID int) (uint64, bool) {
	if steamAppID <= 0 {
		return 0, false
	}
	appMapOnce.Do(loadAppMap)
	n := len(appMap) / recordSize
	if n == 0 {
		return 0, false
	}
	want := uint32(steamAppID)
	i := sort.Search(n, func(i int) bool {
		return binary.LittleEndian.Uint32(appMap[i*recordSize:]) >= want
	})
	if i >= n || binary.LittleEndian.Uint32(appMap[i*recordSize:]) != want {
		return 0, false
	}
	return binary.LittleEndian.Uint64(appMap[i*recordSize+4:]), true
}
